name: CI/CD Pipeline 🚀

on:
  push:
    branches:
      - main # This will trigger the pipeline when changes are pushed to the main branch.

jobs:
  build-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Specify your AWS region.

    - name: Login to AWS ECR
      run: |
        aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 242201301803.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and push Docker image to ECR
      run: 

        # Build, Tag, and Push
        docker build -t mediplus-repo .
        docker tag mediplus-repo:${{ github.run_number }} 242201301803.dkr.ecr.us-east-1.amazonaws.com/meddiplus-repo: ${{ github.run_number }}
        docker push 242201301803.dkr.ecr.us-east-1.amazonaws.com/mediplus-repo:${{ github.run_number }}

  deploy:
    runs-on: ubuntu-latest 
    needs: build-push 
    
    steps:
    - name: check my ssh key 
      run: |
        echo "${{ secrets.SSH_KEY }}" > Dockerhost.pem
        chmod 600 Dockerhost.pem

        ssh -o StrictHostKeyChecking=no -i Dockerhost.pem ubuntu@3.94.110.160 "docker ps"
        ssh -o StrictHostKeyChecking=no -i Dockerhost.pem ubuntu@3.94.110.160 "docker pull 242201301803.dkr.ecr.us-east-1.amazonaws.com/mediplus-repo:${{ github.run_number }}"
        ssh -o StrictHostKeyChecking=no -i Dockerhost.pem ubuntu@3.94.110.160 "hostnamectl"
        ssh -o StrictHostKeyChecking=no -i Dockerhost.pem ubuntu@3.94.110.160 "docker rm -f mediplus-repo"
        # Corrected the trailing double-quote here
        ssh -o StrictHostKeyChecking=no -i Dockerhost.pem ubuntu@3.94.110.160 "docker run -d -p 80:80 242201301803.dkr.ecr.us-east-1.amazonaws.com/mediplus-repo:${{ github.run_number }}"